-- Add columns for extended revenue plan (years 2-5)
ALTER TABLE public.pipeline_entries
ADD COLUMN IF NOT EXISTS jan_y2 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS feb_y2 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS mar_y2 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS apr_y2 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS may_y2 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS jun_y2 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS jul_y2 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS aug_y2 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS sep_y2 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS oct_y2 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS nov_y2 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS dec_y2 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS jan_y3 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS feb_y3 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS mar_y3 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS apr_y3 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS may_y3 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS jun_y3 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS jul_y3 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS aug_y3 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS sep_y3 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS oct_y3 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS nov_y3 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS dec_y3 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS jan_y4 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS feb_y4 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS mar_y4 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS apr_y4 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS may_y4 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS jun_y4 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS jul_y4 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS aug_y4 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS sep_y4 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS oct_y4 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS nov_y4 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS dec_y4 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS jan_y5 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS feb_y5 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS mar_y5 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS apr_y5 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS may_y5 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS jun_y5 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS jul_y5 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS aug_y5 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS sep_y5 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS oct_y5 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS nov_y5 NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS dec_y5 NUMERIC DEFAULT 0;

-- Add OTC entries as JSONB column
ALTER TABLE public.pipeline_entries
ADD COLUMN IF NOT EXISTS otc_entries JSONB DEFAULT '[]'::jsonb;

-- Add telkom_name column
ALTER TABLE public.pipeline_entries
ADD COLUMN IF NOT EXISTS telkom_name TEXT;
